### ISSUE TITLE
Windows 10 launch issue

### ISSUE THREAD

**Issue by DiscoPhreak** [sonoUnoTeam/sonoUno-desktop#3]
I am on a Windows 10 machine and when I run python SonoUno I get the below error. I have followed the instructions on the github and on the PDF provided at https://www.sonouno.org.ar/installation-manuals/

I tried reinstalling everything just to make sure I didn't miss any steps and things look to be in place. I can confirm that I have Octave 7.2.0 installed with Python 3.10.6 installed.

Any suggestions?

D:\Sonification\sonoUno-master\sonoUno>python sonoUno
Traceback (most recent call last):
  File "D:\Sonification\sonoUno-master\sonoUno\sonoUno", line 11, in <module>
    import gui.frame_implementation as gui
  File "D:\Sonification\sonoUno-master\sonoUno\gui\frame_implementation.py", line 16, in <module>
    import oct2py
  File "C:\Users\(USERNAME)\AppData\Local\Programs\Python\Python310\lib\site-packages\oct2py\__init__.py", line 38, in <module>
    octave = Oct2Py()
  File "C:\Users\(USERNAME)\AppData\Local\Programs\Python\Python310\lib\site-packages\oct2py\core.py", line 83, in __init__
    self.restart()
  File "C:\Users\(USERNAME)\AppData\Local\Programs\Python\Python310\lib\site-packages\oct2py\core.py", line 533, in restart
    self._engine = OctaveEngine(stdin_handler=self._handle_stdin,
  File "C:\Users\(USERNAME)\AppData\Local\Programs\Python\Python310\lib\site-packages\octave_kernel\kernel.py", line 173, in __init__
    self.executable = self._get_executable()
  File "C:\Users\(USERNAME)\AppData\Local\Programs\Python\Python310\lib\site-packages\octave_kernel\kernel.py", line 472, in _get_executable
    raise OSError('octave not found, please see README')
OSError: octave not found, please see README

**Comment by johicasado** [comment]
Hello, in general python and octave present complications on Windows environment, could you confirm please if you have the octave path in the Windows System Variables? 

Control Panel -> System and Security -> System -> Advance system settings -> Environment Variables
