### ISSUE TITLE
Ubuntu 20.04 Window resizing error

### ISSUE THREAD

**Issue by nhurleywalker** [sonoUnoTeam/sonoUno-desktop#4]
Hi there,

I've installed sonouno via github since I had errors when I tried to use pip(3). When I run it, I get the following error:

```tash@samantha:~/Programs/sonoUno/sonoUno$ python3 sonoUno
/home/tash/lib/python3.8/site-packages/oct2py-5.5.1-py3.8.egg/oct2py/io.py:249: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is 0 and self.size==1:
/home/tash/Programs/sonoUno/sonoUno/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exception_error.find('No such file or directory') is not -1 or exception_error.find('No existe el archivo o el directorio') is not -1:
/home/tash/Programs/sonoUno/sonoUno/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exception_error.find('No such file or directory') is not -1 or exception_error.find('No existe el archivo o el directorio') is not -1:
pygame 2.1.3.dev6 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "sonoUno", line 39, in <module>
    frame = SonoUnoCore()
  File "sonoUno", line 27, in __init__
    gui.SonoUnoGUI.__init__(self)
  File "/home/tash/Programs/sonoUno/sonoUno/gui/frame_implementation.py", line 45, in __init__
    gui.FrameDesign.__init__(self)
  File "/home/tash/Programs/sonoUno/sonoUno/gui/frame_design.py", line 186, in __init__
    self._displaypanel = self._createdisplaypanel(self._rightpanel)
  File "/home/tash/Programs/sonoUno/sonoUno/gui/frame_design.py", line 2348, in _createdisplaypanel
    self._graphicPanel.SetSizer( _matplotlibSizer )
wx._core.wxAssertionError: C++ assertion "CheckExpectedParentIs(w, m_containingWindow)" failed at /tmp/easy_install-rttxev91/wxPython-4.2.0/ext/wxWidgets/src/common/sizer.cpp(887) in SetContainingWindow(): Windows managed by the sizer associated with the given window must have this window as parent, otherwise they will not be repositioned correctly.

Please use the window wxPanel@0x47f7000 ("panel") with which this sizer is associated, as the parent when creating the window wxScrolledWindow@0x4b06090 ("panel") managed by it.
```

I'm not sure what the issue is or how to fix it; hope you can help.
Thanks,
Natasha

**Comment by johicasado** [comment]
Hello Natasha, is a fact that sonoUno have problems with Python 3.10 and wxPython, I'll fix it and go back to you with any news!

If you want to give a chance and try it with one of the first version of Python 3.9, I think that works fine, I yesterday run sonoUno with python 3.8 on Ubuntu 20.04 and works fine. 

In any case, I will let you know when I fix sonoUno to works with Python 3.10, I think is a wxPython update problem.

Thank you very much!!
Johanna.

**Comment by johicasado** [comment]
Hello again Natasha, the problem was solved, could you let me know if you be able to run the new update of sonoUno?

**Comment by nhurleywalker** [comment]
Hi Johanna,
Thanks for getting back to me! I git pulled, installed again, and tried running it again but got this error:
```/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/data_export/data_export.py:77: SyntaxWarning: "is not" with a literal. Did you mean "!="?
pygame 2.1.3.dev6 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/tash/bin/sonoUno", line 4, in <module>
    __import__('pkg_resources').run_script('sonoUno==3.1.0', 'sonoUno')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/EGG-INFO/scripts/sonoUno", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/tash/lib/python3.8/site-packages/sonoUno-3.1.0-py3.8.egg/gui/frame_implementation.py", line 29, in <module>
ModuleNotFoundError: No module named 'data_lhc'
```
I tried pip3 install data_lhc but there's no such module. Thanks for looking into this!
Natasha

**Comment by johicasado** [comment]
Hi Natasha, 
the module data_lhc should be downloaded when you clone the git repository, could you check if you have it inside the sonoUno folder located inside the cloned repository?

**Comment by johicasado** [comment]
Thank you very much, if you need anything else you could open another issue.
